image:
  file: .gitpod.Dockerfile
# GitHub
github:
  prebuilds:
    master: false
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
# Commands to start on workspace startup
tasks:
  - name: Submodule Update
    env: 
      REF: master
    before: |
      git submodule update --init --recursive && git submodule update --remote 
      git checkout "$REF" || true
      git submodule foreach "git checkout $REF || true"
  - name: Build & Run
    command: ./bin/kms-build-run.sh --dbg
ports:
  # WebSocket (ws:// & wss://)
  - port: 8888
  - port: 8433