image:
  file: .gitpod.Dockerfile
# GitHub
github:
  prebuilds:
    master: false
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
# Commands to start on workspace startup
tasks:
  - before: |
    git submodule update --init --recursive
    git submodule update --remote 
  - env: 
      REF: master
    before: |
      git checkout "$REF" || true
      git submodule foreach "git checkout $REF || true"
  - command: sudo ./bin/kms-build-run.sh --dbg