image:
  file: .gitpod.Dockerfile
# GitHub
github:
  prebuilds:
    master: false
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
# Commands to start on workspace startup
tasks:
  - name: Submodule Update
    env: 
      REF: master
    before: |
      git submodule update --init --recursive && git submodule update --remote 
      git checkout "$REF" || true
      git submodule foreach "git checkout $REF || true"
  - name: Build
    command: ./bin/kms-build-run.sh --build-only
  # - name: Use Secure WebSocket (self-signed)
  #   command: |
  #     cp kurento-media-server/test/testCertificate.pem build-Debug/config/cert+key.pem
  #     sed -i -E 's/\/\/(port|certificate)/\1/g' ./build-Debug/config/kurento.conf.json
  - name: Run
    command: ./bin/kms-build-run.sh
ports:
  # WebSocket (ws:// & wss://)
  - port: 8888
  # Only supports HTTP
  # https://www.gitpod.io/docs/config-ports
  # - port: 8433
  #   onOpen: open-browser